const currenciesCodesAndSymbols = <String, String>{
  'AFN': '؋',
  'ALL': 'L',
  'DZD': 'د.ج',
  'AOA': 'Kz',
  'ARS': r'$',
  'AUD': r'$',
  'AZN': '₼',
  'BSD': r'$',
  'BHD': '.د.ب',
  'BDT': '৳',
  'BBD': r'$',
  'BYN': 'Br',
  'BZD': r'$',
  'XOF': 'Fr',
  'BMD': r'$',
  'BTN': 'Nu.',
  'BOB': 'Bs.',
  'BAM': 'KM',
  'BWP': 'P',
  'BRL': r'R$',
  'BND': r'$',
  'BGN': 'лв',
  'BIF': 'Fr',
  'KHR': '៛',
  'CAD': r'$',
  'CVE': 'Esc',
  'KYD': r'$',
  'XAF': 'Fr',
  'CLP': r'$',
  'CNY': '¥',
  'COP': r'$',
  'KMF': 'Fr',
  'CDF': 'Fr',
  'CRC': '₡',
  'HRK': 'kn',
  'CUP': r'$',
  'CYP': '£',
  'CZK': 'Kč',
  'DKK': 'kr',
  'DJF': 'Fr',
  'DOP': r'$',
  'XCD': r'$',
  'EGP': '£',
  'ERN': 'Nkf',
  'ETB': 'Br',
  'EUR': '€',
  'FKP': '£',
  'FJD': r'$',
  'GMD': 'D',
  'GEL': '₾',
  'GHS': '₵',
  'GIP': '£',
  'GTQ': 'Q',
  'GNF': 'Fr',
  'GYD': r'$',
  'HTG': 'G',
  'HNL': 'L',
  'HKD': r'$',
  'HUF': 'Ft',
  'ISK': 'kr',
  'INR': '₹',
  'IDR': 'Rp',
  'IRR': '﷼',
  'IQD': 'ع.د',
  'ILS': '₪',
  'JMD': r'$',
  'JPY': '¥',
  'JOD': 'د.ا',
  'KZT': '₸',
  'KES': 'Sh',
  'KWD': 'د.ك',
  'KGS': 'лв',
  'LAK': '₭',
  'LBP': 'ل.ل',
  'LSL': 'L',
  'LRD': r'$',
  'LYD': 'ل.د',
  'MOP': 'P',
  'MKD': 'ден',
  'MGA': 'Ar',
  'MWK': 'MK',
  'MYR': 'RM',
  'MVR': '.ރ',
  'MRU': 'UM',
  'MUR': '₨',
  'MXN': r'$',
  'MDL': 'L',
  'MNT': '₮',
  'MAD': 'د.م.',
  'MZN': 'MT',
  'MMK': 'K',
  'NAD': r'$',
  'NPR': '₨',
  'ANG': 'ƒ',
  'NZD': r'$',
  'NIO': r'C$',
  'NGN': '₦',
  'KPW': '₩',
  'NOK': 'kr',
  'OMR': 'ر.ع.',
  'PKR': '₨',
  'PAB': 'B/.',
  'PGK': 'K',
  'PYG': '₲',
  'PEN': 'S/',
  'PHP': '₱',
  'PLN': 'zł',
  'QAR': 'ر.ق',
  'RON': 'lei',
  'RUB': '₽',
  'RWF': 'Fr',
  'SHP': '£',
  'WST': 'T',
  'STN': 'Db',
  'SAR': 'ر.س',
  'RSD': 'din',
  'SCR': '₨',
  'SLL': 'Le',
  'SGD': r'$',
  'SBD': r'$',
  'SOS': 'Sh',
  'ZAR': 'R',
  'KRW': '₩',
  'SSP': '£',
  'LKR': 'Rs',
  'SDG': '£',
  'SRD': r'$',
  'SZL': 'L',
  'SEK': 'kr',
  'CHF': 'Fr',
  'SYP': '£',
  'TWD': r'$',
  'TJS': 'ЅМ',
  'TZS': 'Sh',
  'THB': '฿',
  'TOP': r'T$',
  'TTD': r'$',
  'TND': 'د.ت',
  'TRY': '₺',
  'TMT': 'm',
  'UGX': 'Sh',
  'UAH': '₴',
  'AED': 'د.إ',
  'GBP': '£',
  'USD': r'$',
  'UYU': r'$',
  'UZS': 'лв',
  'VUV': 'Vt',
  'VES': 'Bs.',
  'VND': '₫',
  'YER': '﷼',
  'ZMW': 'ZK',
  'ZWL': r'$',
};

const commonCurrencies = [
  'USD',
  'EUR',
  'JPY',
  'GBP',
  'AUD',
  'CAD',
  'CHF',
  'CNY',
  'HKD',
  'NZD',
];

String getCurrencySymbol(String currencyCode) {
  return currenciesCodesAndSymbols[currencyCode] ?? '';
}
