// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYcKq74EAVLTYH0x6vkkGCLm5Luardho',
    appId: '1:493902487548:android:3f9cc1ab778f14e9a35c79',
    messagingSenderId: '493902487548',
    projectId: 'tracking-app-4f63b',
    storageBucket: 'tracking-app-4f63b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zMDXGJptKb5zV99u4n2XD7m8Zqt78Vk',
    appId: '1:493902487548:ios:a0d738922afbd9ada35c79',
    messagingSenderId: '493902487548',
    projectId: 'tracking-app-4f63b',
    storageBucket: 'tracking-app-4f63b.appspot.com',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2zMDXGJptKb5zV99u4n2XD7m8Zqt78Vk',
    appId: '1:493902487548:ios:c7b6c0e119c78314a35c79',
    messagingSenderId: '493902487548',
    projectId: 'tracking-app-4f63b',
    storageBucket: 'tracking-app-4f63b.appspot.com',
    iosBundleId: 'com.example.trackingApp.RunnerTests',
  );
}
